---
- name: Bootstrap Docker hosts
  ansible.builtin.import_playbook: ../../../../molecule/shared/prepare-docker.yml

- name: Prepare user role test prerequisites
  ansible.builtin.import_playbook: ../shared/prepare.yml
