FROM archlinux:base

ENV container=docker

RUN pacman -Syu --noconfirm python sudo && \
    rm -rf /var/cache/pacman/pkg/*

# Restore glibc locale data stripped by NoExtract in the base image,
# so roles that test locale generation have the definition files available.
RUN sed -i '/^NoExtract/d' /etc/pacman.conf && \
    pacman -S --noconfirm --overwrite='*' glibc && \
    rm -rf /var/cache/pacman/pkg/*

RUN (for i in /lib/systemd/system/sysinit.target.wants/*; do \
      [ "$i" = "/lib/systemd/system/sysinit.target.wants/systemd-tmpfiles-setup.service" ] || rm -f "$i"; \
    done); \
    rm -f /lib/systemd/system/multi-user.target.wants/*; \
    rm -f /etc/systemd/system/*.wants/*; \
    rm -f /lib/systemd/system/local-fs.target.wants/*; \
    rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
    rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
    rm -f /lib/systemd/system/basic.target.wants/*

STOPSIGNAL SIGRTMIN+3
VOLUME ["/sys/fs/cgroup", "/tmp", "/run"]
CMD ["/usr/lib/systemd/systemd"]
