---
# === Internal role details ===

_teleport_supported_distributions:
  - Archlinux
  - Ubuntu
  - Fedora
  - Void
  - Gentoo

_teleport_supported_modes:
  - standalone
  - agent

_teleport_service_name: teleport
_teleport_architecture_map:
  x86_64: amd64
  aarch64: arm64
  armv7l: arm
  i686: '386'
_teleport_architecture: "{{ _teleport_architecture_map[ansible_facts['architecture']] }}"
_teleport_binary_names:
  - teleport
  - tctl
  - tsh
  - tbot
  - fdpass-teleport
  - teleport-update
