---
# === /etc/hosts report ===

- name: "Report: Hosts FQDN entry"
  ansible.builtin.include_role:
    name: common
    tasks_from: report_phase.yml
  vars:
    common_rpt_fact: "_hostname_phases"
    common_rpt_phase: "Configure /etc/hosts"
    common_rpt_detail: "127.0.1.1 {{ hostname_name }}.{{ hostname_domain }} {{ hostname_name }}"
  when: hostname_domain | length > 0
  tags: ['hostname', 'report']

- name: "Report: Hosts short entry"
  ansible.builtin.include_role:
    name: common
    tasks_from: report_phase.yml
  vars:
    common_rpt_fact: "_hostname_phases"
    common_rpt_phase: "Configure /etc/hosts"
    common_rpt_detail: "127.0.1.1 {{ hostname_name }}"
  when: hostname_domain | length == 0
  tags: ['hostname', 'report']
