---
- name: Prepare Docker container
  ansible.builtin.import_playbook: ../../../../molecule/shared/prepare-docker.yml

- name: Prepare chezmoi test environment
  ansible.builtin.import_playbook: ../shared/prepare.yml
