---
# === teleport: configure phase ===

- name: Render Teleport configuration
  ansible.builtin.template:
    src: teleport.yaml.j2
    dest: /etc/teleport.yaml
    owner: root
    group: root
    mode: "0600"
  register: _teleport_configuration
  no_log: true
