---
# === teleport: configure phase ===

- name: Ensure Teleport data directory exists
  ansible.builtin.file:
    path: /var/lib/teleport
    state: directory
    owner: root
    group: root
    mode: "0750"

- name: Render Teleport configuration
  ansible.builtin.template:
    src: teleport.yaml.j2
    dest: /etc/teleport.yaml
    owner: root
    group: root
    mode: "0600"
  register: _teleport_configuration
  no_log: true
