---
# === /etc/hosts verification ===

- name: Read /etc/hosts
  ansible.builtin.slurp:
    src: /etc/hosts
  register: _hostname_hosts_file
  tags: ['hostname']

- name: Assert /etc/hosts contains FQDN hostname entry
  ansible.builtin.assert:
    that:
      - "('127.0.1.1 ' ~ hostname_name ~ '.' ~ hostname_domain ~ ' ' ~ hostname_name) in ((_hostname_hosts_file.content | b64decode).split('\n'))"
    fail_msg: >-
      /etc/hosts is missing expected line
      '127.0.1.1 {{ hostname_name }}.{{ hostname_domain }} {{ hostname_name }}'.
    success_msg: >-
      /etc/hosts contains
      '127.0.1.1 {{ hostname_name }}.{{ hostname_domain }} {{ hostname_name }}'
    quiet: true
  when: hostname_domain | length > 0
  tags: ['hostname']

- name: Assert /etc/hosts contains short hostname entry
  ansible.builtin.assert:
    that:
      - "('127.0.1.1 ' ~ hostname_name) in ((_hostname_hosts_file.content | b64decode).split('\n'))"
    fail_msg: >-
      /etc/hosts is missing expected line '127.0.1.1 {{ hostname_name }}'.
    success_msg: "/etc/hosts contains '127.0.1.1 {{ hostname_name }}'"
    quiet: true
  when: hostname_domain | length == 0
  tags: ['hostname']
