---
# === Таймзона ===
# Установка системной таймзоны
# Дистро-агностик, инит-агностик

- name: Timezone role
  when: timezone_enabled | bool
  tags: ['timezone']
  block:

    - name: Run timezone preflight
      ansible.builtin.include_tasks: assert.yml
      tags: ['timezone']

    - name: Install timezone database
      ansible.builtin.include_tasks: install.yml
      tags: ['timezone']

    - name: Set system timezone
      ansible.builtin.include_tasks: set_timezone.yml
      tags: ['timezone']

    - name: Restart cron for timezone change
      ansible.builtin.include_tasks: restart_cron.yml
      tags: ['timezone']

    - name: Verify timezone
      ansible.builtin.include_tasks: verify.yml
      tags: ['timezone']

    - name: Render timezone execution report
      ansible.builtin.include_tasks: report.yml
      tags: ['timezone', 'report']
