---
- name: Bootstrap Vagrant VM
  ansible.builtin.import_playbook: ../../../../molecule/shared/prepare-vagrant.yml

- name: Prepare test prerequisites
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Install pciutils
      community.general.pacman:
        name: pciutils
        state: present
      when: ansible_facts['os_family'] == 'Archlinux'

    - name: Install pciutils
      ansible.builtin.apt:
        name: pciutils
        state: present
      when: ansible_facts['os_family'] == 'Debian'
