---
- name: Restart caddy
  community.docker.docker_compose_v2:
    project_src: "{{ caddy_base_dir }}"
    state: restarted
  listen: Restart caddy

- name: Reload caddy
  ansible.builtin.command:
    cmd: docker exec caddy caddy reload --config /etc/caddy/Caddyfile
  register: _caddy_reload_result
  changed_when: _caddy_reload_result.rc == 0
  failed_when: _caddy_reload_result.rc != 0
  listen: Reload caddy
