---
- name: Bootstrap Vagrant VM
  ansible.builtin.import_playbook: ../../../../molecule/shared/prepare-vagrant.yml

- name: Prepare ssh-keygen runtime
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Install OpenSSH client tools
      ansible.builtin.package:
        name: "{{ 'openssh-client' if ansible_facts['os_family'] == 'Debian' else 'openssh' }}"
        state: present

- name: Prepare ssh_keys test user
  ansible.builtin.import_playbook: ../shared/prepare.yml
