

const BOOT = {
    BOOT_INITIAL_DELAY: 300,
  PERIPHERAL_DELAY: 600,
  PHASE_GAP: 300,
  FINAL_SETTLE: 100,
}

const AUTH = {
  AUTH_MESSAGE_DISPLAY: 3000,
  AUTH_RETRY_DELAY: 1000,
  SESSION_LAUNCH_DELAY: 500,
}

const TYPEWRITER = {
    CHAR_DELAY: 18,
    LINE_PAUSE: 400,
}

const FINGERPRINT = {
    SCRAMBLE_FRAMES: 15,
    SCRAMBLE_INTERVAL: 60,
}

const SVG3D = {
  ROTATION_SLOW: 12000,
  ROTATION_FAST: 4000,
  PULSE_DURATION: 2000,
  SHAKE_DURATION: 100,
  BOUNCE_DURATION: 600,
  FLOAT_DURATION: 2000,
}

export const TIMINGS = {

  BOOT,
  AUTH,
  TYPEWRITER,
  FINGERPRINT,
  SVG3D,

  // Clock
  CLOCK_TICK: 1000,

  // Cube
  CUBE_PERIOD: 12000,
} as const;