"""LightDM config deployment strategy."""

import subprocess
from pathlib import Path

from .strategies import DeployStrategy


class LightDMConfigDeployStrategy(DeployStrategy):
    """Deploy LightDM configuration pointing to display setup hook."""
    
    LIGHTDM_CONF_DIR = Path("/etc/lightdm/lightdm.conf.d")
    LIGHTDM_CONF_FILE = "50-display-setup.conf"
    HOOK_SCRIPT_PATH = "/etc/lightdm/display-setup-hook.sh"
    
    def deploy(self) -> bool:
        """Create LightDM config file pointing to hook script."""
        try:
            config_content = f"""# Autogenerated LightDM display setup configuration
# Created by bootstrap display manager

[Seat:*]
display-setup-script={self.HOOK_SCRIPT_PATH}
"""

            config_path = self.LIGHTDM_CONF_DIR / self.LIGHTDM_CONF_FILE

            # Create directory with sudo
            subprocess.run(
                ["sudo", "mkdir", "-p", str(self.LIGHTDM_CONF_DIR)],
                check=True,
                capture_output=True
            )

            # Write file with sudo using tee
            subprocess.run(
                ["sudo", "tee", str(config_path)],
                input=config_content,
                text=True,
                check=True,
                capture_output=True
            )

            # Set permissions with sudo
            subprocess.run(
                ["sudo", "chmod", "0644", str(config_path)],
                check=True,
                capture_output=True
            )

            self.logger.info(f"Created LightDM config: {config_path}")
            return True

        except subprocess.CalledProcessError as e:
            self.logger.error(f"Failed to create LightDM config via sudo: {e}")
            return False
        except Exception as e:
            self.logger.error(f"Failed to create LightDM config: {e}")
            return False
