"""LightDM hook deployment strategy."""

import subprocess
from pathlib import Path

from .strategies import DeployStrategy


class LightDMHookDeployStrategy(DeployStrategy):
    """Deploy LightDM display setup hook script."""
    
    HOOK_SCRIPT_PATH = Path("/etc/lightdm/display-setup-hook.sh")
    
    def deploy(self) -> bool:
        """Create LightDM display setup hook with xrandr commands."""
        if not self.manager._primary_monitor:
            self.logger.error("No primary monitor detected, cannot create hook")
            return False

        try:
            hook_content = self._generate_hook_script()

            # Create parent directory with sudo
            subprocess.run(
                ["sudo", "mkdir", "-p", str(self.HOOK_SCRIPT_PATH.parent)],
                check=True,
                capture_output=True
            )

            # Write file with sudo using tee
            subprocess.run(
                ["sudo", "tee", str(self.HOOK_SCRIPT_PATH)],
                input=hook_content,
                text=True,
                check=True,
                capture_output=True
            )

            # Set executable permissions with sudo
            subprocess.run(
                ["sudo", "chmod", "0755", str(self.HOOK_SCRIPT_PATH)],
                check=True,
                capture_output=True
            )

            self.logger.info(f"Created LightDM hook: {self.HOOK_SCRIPT_PATH}")
            return True

        except subprocess.CalledProcessError as e:
            self.logger.error(f"Failed to create LightDM hook via sudo: {e}")
            return False
        except Exception as e:
            self.logger.error(f"Failed to create LightDM hook: {e}")
            return False
    
    def _generate_hook_script(self) -> str:
        """Generate hook script content with xrandr commands."""
        monitor_name = self.manager._primary_monitor.name
        
        script = f"""#!/bin/bash
# Autogenerated LightDM display setup hook
# Created by bootstrap display manager
# This script is executed before LightDM greeter appears

# Wait for X server to be ready
sleep 1

# Add custom modeline and set display resolution
xrandr --newmode "{self.manager._modeline_name}" {self.manager._modeline_params} 2>/dev/null || true
xrandr --addmode {monitor_name} "{self.manager._modeline_name}" 2>/dev/null || true
xrandr --output {monitor_name} --mode "{self.manager._modeline_name}" --primary 2>/dev/null || true
"""
        return script
