---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  roles:
    - role: xorg
      vars:
        dotfiles_base_dir: /tmp/xorg_test_dotfiles
        xorg_monitor_mode: >-
          {{ '2560x1440_60.00' if 'xorg_fixed' in group_names else 'auto' }}
        xorg_monitor_modeline: >-
          {{
            '312.25 2560 2752 3024 3488 1440 1443 1448 1493 -hsync +vsync'
            if 'xorg_fixed' in group_names
            else ''
          }}
