---
# === gpu_drivers / install / AMD ===

- name: "Install AMD drivers"
  ansible.builtin.include_tasks:
    file: common/install_packages.yml
  vars:
    _gpu_drivers_package_stack: "{{ _gpu_drivers_archlinux_amd }}"

- name: "Install AMD multilib"
  ansible.builtin.include_tasks:
    file: common/install_packages.yml
  vars:
    _gpu_drivers_package_stack: "{{ _gpu_drivers_archlinux_amd_multilib }}"
  when: gpu_drivers_multilib
