---
# === gpu_drivers / install / common ===

- name: "Install Vulkan ICD loader"
  ansible.builtin.include_tasks:
    file: common/install_packages.yml
  vars:
    _gpu_drivers_package_stack: "{{ _gpu_drivers_archlinux_vulkan_common }}"

- name: "Install Vulkan ICD loader multilib"
  ansible.builtin.include_tasks:
    file: common/install_packages.yml
  vars:
    _gpu_drivers_package_stack: "{{ _gpu_drivers_archlinux_vulkan_common_multilib }}"
  when: gpu_drivers_multilib

- name: "Install Vulkan tools"
  ansible.builtin.include_tasks:
    file: common/install_packages.yml
  vars:
    _gpu_drivers_package_stack: "{{ _gpu_drivers_archlinux_vulkan_tools }}"
  when: gpu_drivers_vulkan_tools
