#!/usr/bin/env bash
set -euo pipefail

# mirror/ubuntu.sh
# Ubuntu/Debian mirror selection via apt-mirror or sources.list editing.
# Supports country-based selection and mirror validation.

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
. "$SCRIPT_DIR/mirror-common.sh" || exit 1

# Detect Ubuntu/Debian release
if [ -f /etc/os-release ]; then
  . /etc/os-release
  RELEASE_NAME="${VERSION_CODENAME:-focal}"
else
  RELEASE_NAME="focal"
fi

log_info "detected release: $RELEASE_NAME"

# List of Ubuntu mirrors for supported countries
# Supported countries: KZ, RU, DE, FR, NL
declare -a UBUNTU_MIRRORS=(
  "archive.ubuntu.com"
  "security.ubuntu.com"
  "de.archive.ubuntu.com"
  "fr.archive.ubuntu.com"
  "ru.archive.ubuntu.com"
)

# Map country codes to preferred mirrors
declare -A COUNTRY_MIRRORS=(
  [KZ]="ru.archive.ubuntu.com"
  [RU]="ru.archive.ubuntu.com"
  [DE]="de.archive.ubuntu.com"
  [FR]="fr.archive.ubuntu.com"
  [NL]="archive.ubuntu.com"
)

# Select primary mirror based on country or use default
PRIMARY_MIRROR="archive.ubuntu.com"
if [ -n "${MIRROR_COUNTRY:-}" ] && [ -n "${COUNTRY_MIRRORS[${MIRROR_COUNTRY}]:-}" ]; then
  PRIMARY_MIRROR="${COUNTRY_MIRRORS[$MIRROR_COUNTRY]}"
  log_info "selected mirror for country ${MIRROR_COUNTRY}: $PRIMARY_MIRROR"
fi

# Test mirror accessibility if validation is enabled
if [ "${MIRROR_VALIDATE:-0}" = "1" ]; then
  log_info "validating mirror accessibility..."
  PROTOCOL="${MIRROR_PROTOCOL:-https}"
  TEST_URL="${PROTOCOL}://${PRIMARY_MIRROR}/ubuntu/dists/${RELEASE_NAME}/Release"
  
  if validate_mirror "$TEST_URL"; then
    log_info "mirror validation successful: $PRIMARY_MIRROR"
  else
    log_warn "mirror validation failed for $PRIMARY_MIRROR, using default"
    PRIMARY_MIRROR="archive.ubuntu.com"
  fi
fi

# Backup current sources.list
SOURCES_LIST="/etc/apt/sources.list"
if [ -f "$SOURCES_LIST" ]; then
  BACKUP_FILE=$(backup_file "$SOURCES_LIST")
fi

# Generate new sources.list with selected mirror
log_info "generating new sources.list with mirror: $PRIMARY_MIRROR"
PROTOCOL="${MIRROR_PROTOCOL:-https}"

cat > "$SOURCES_LIST" << EOF
# Ubuntu/Debian sources automatically generated by mirror-manager
# Primary mirror: $PRIMARY_MIRROR
# Release: $RELEASE_NAME

deb $PROTOCOL://$PRIMARY_MIRROR/ubuntu $RELEASE_NAME main restricted universe multiverse
deb $PROTOCOL://$PRIMARY_MIRROR/ubuntu $RELEASE_NAME-updates main restricted universe multiverse
deb $PROTOCOL://$PRIMARY_MIRROR/ubuntu $RELEASE_NAME-backports main restricted universe multiverse
deb $PROTOCOL://security.ubuntu.com/ubuntu $RELEASE_NAME-security main restricted universe multiverse
EOF

log_info "sources.list updated successfully"

# Attempt to update package cache
log_info "refreshing package cache..."
if apt update -y 2>&1; then
  log_info "package cache refreshed successfully"
else
  log_warn "package cache refresh had issues"
  
  # Try with just update (no key verification issues)
  if apt update -y --allow-insecure-repositories 2>&1 || true; then
    log_info "package cache updated with relaxed verification"
  else
    log_error "package cache update failed"
    
    # Restore backup
    if [ -n "${BACKUP_FILE:-}" ] && [ -f "$BACKUP_FILE" ]; then
      log_warn "restoring previous sources.list from backup"
      restore_from_backup "$BACKUP_FILE"
    fi
    exit 1
  fi
fi

log_info "ubuntu mirror selection complete"
