#!/bin/bash
# ============================================================
# Workspace-Add Button X Offset Calculator
# Outputs X position in pixels, updates on i3 workspace events
# Used by ewwii listen() for dynamic button positioning
# ============================================================

set -euo pipefail

# Source layout constants (generated by chezmoi)
source ~/.config/layout-constants.sh 2>/dev/null || {
    # Fallback values if constants not available
    EDGE_PADDING=12
    ICON_WIDTH=16
    SEP_GAP=22
    GAPS_OUTER=8
    WS_ADD_GAP=4
    MIN_WORKSPACES=3
}

calc_offset() {
    local ws_count
    ws_count=$(i3-msg -t get_workspaces 2>/dev/null | jq 'length' 2>/dev/null || echo 3)

    # Enforce minimum workspaces
    [[ $ws_count -lt $MIN_WORKSPACES ]] && ws_count=$MIN_WORKSPACES

    # Calculate workspace bar width first
    local ws_width=$((2 * EDGE_PADDING + ws_count * ICON_WIDTH + (ws_count - 1) * SEP_GAP))

    # Add button offset = gaps_outer + ws_width + ws_add_gap
    echo $((GAPS_OUTER + ws_width + WS_ADD_GAP))
}

# Initial output
calc_offset

# Subscribe to workspace events and recalculate on changes
i3-msg -t subscribe '["workspace"]' --monitor 2>/dev/null | while read -r _; do
    calc_offset
done
