#!/bin/bash
# ============================================================
# Workspace Bar Width Calculator
# Outputs width in pixels, updates on i3 workspace events
# Used by ewwii listen() for dynamic window sizing
# ============================================================

set -euo pipefail

# Source layout constants (generated by chezmoi)
source ~/.config/layout-constants.sh 2>/dev/null || {
    # Fallback values if constants not available
    EDGE_PADDING=12
    ICON_WIDTH=16
    SEP_GAP=22
    MIN_WORKSPACES=3
}

calc_width() {
    local ws_count
    ws_count=$(i3-msg -t get_workspaces 2>/dev/null | jq 'length' 2>/dev/null || echo 3)

    # Enforce minimum workspaces
    [[ $ws_count -lt $MIN_WORKSPACES ]] && ws_count=$MIN_WORKSPACES

    # Formula: 2*edge_padding + ws_count*icon_width + (ws_count-1)*gap
    echo $((2 * EDGE_PADDING + ws_count * ICON_WIDTH + (ws_count - 1) * SEP_GAP))
}

# Initial output
calc_width

# Subscribe to workspace events and recalculate on changes
i3-msg -t subscribe '["workspace"]' --monitor 2>/dev/null | while read -r _; do
    calc_width
done
