---
- name: Verify fail2ban role
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Validate fail2ban configuration syntax
      ansible.builtin.command:
        cmd: fail2ban-server --test
      register: _fail2ban_verify_config
      changed_when: false
