---
# === /etc/hosts phase ===

- name: Configure hostname hosts entry
  ansible.builtin.include_tasks: configure/hosts.yml
  tags: ['hostname']

- name: Verify hostname hosts entry
  ansible.builtin.include_tasks: verify/hosts.yml
  tags: ['hostname']

- name: Report hostname hosts entry
  ansible.builtin.include_tasks: report/hosts.yml
  tags: ['hostname', 'report']
