---
- name: Prepare Docker hosts
  ansible.builtin.import_playbook: ../../../../molecule/shared/prepare-docker.yml

- name: Prepare Git target user
  ansible.builtin.import_playbook: ../shared/prepare.yml
