---
- name: Prepare firewall containers
  ansible.builtin.import_playbook: ../../../../molecule/shared/prepare-docker.yml

- name: Prepare firewall role prerequisites
  ansible.builtin.import_playbook: ../shared/prepare.yml
