---
- name: Verify timezone role
  hosts: all
  become: true
  gather_facts: true
  vars:
    timezone_name: "Asia/Almaty"

  tasks:
    - name: Load timezone verification prerequisites
      ansible.builtin.import_role:
        name: timezone
        tasks_from: assert.yml

    - name: Run timezone in-role verification
      ansible.builtin.import_role:
        name: timezone
        tasks_from: verify.yml
