---
# === gpu_drivers / verify / Intel ===

- name: "Assert Intel packages are installed"
  ansible.builtin.include_tasks:
    file: common/verify_packages.yml
  vars:
    _gpu_drivers_package_stack: "{{ _gpu_drivers_debian_intel }}"
