---
# === gpu_drivers / verify / VA-API ===

- name: "Assert NVIDIA VA-API packages are installed"
  ansible.builtin.include_tasks:
    file: common/verify_packages.yml
  vars:
    _gpu_drivers_package_stack: "{{ _gpu_drivers_debian_nvidia_vaapi }}"
  when: gpu_drivers_has_nvidia

- name: "Assert AMD VA-API packages are installed"
  ansible.builtin.include_tasks:
    file: common/verify_packages.yml
  vars:
    _gpu_drivers_package_stack: "{{ _gpu_drivers_debian_amd_vaapi }}"
  when: gpu_drivers_has_amd

- name: "Assert Intel VA-API packages are installed"
  ansible.builtin.include_tasks:
    file: common/verify_packages.yml
  vars:
    _gpu_drivers_package_stack:
      - intel-media-va-driver
  when: gpu_drivers_has_intel
