---
- name: Prepare
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Run OS-specific prepare tasks
      ansible.builtin.include_tasks: "prepare_{{ ansible_facts['os_family'] | lower }}.yml"
