---
# === git: load platform variables ===

- name: Load distro-specific git variables
  ansible.builtin.include_vars: "distro/{{ ansible_facts['os_family'] | lower }}/main.yml"

- name: "Report: Load git vars"
  ansible.builtin.include_role:
    name: common
    tasks_from: report_phase.yml
  vars:
    common_rpt_fact: "_git_phases"
    common_rpt_phase: "Load vars"
    common_rpt_detail: "family={{ ansible_facts['os_family'] }}"
