---
- name: Bootstrap Vagrant VM
  ansible.builtin.import_playbook: ../../../../molecule/shared/prepare-vagrant.yml

- name: Prepare shell target user
  ansible.builtin.import_playbook: ../shared/prepare.yml
