---
- name: Initialize chezmoi configuration
  become: true
  become_user: "{{ target_user }}"
  ansible.builtin.command:
    argv: >-
      {{
        ['/usr/bin/chezmoi', '--force', '--no-tty', 'init',
         '--promptChoice', 'Choose color theme=' ~ chezmoi_theme_name]
        + (['--branch', chezmoi_repo_ref] if chezmoi_repo_ref | length > 0 else [])
        + [chezmoi_repo_url]
      }}
    chdir: "{{ getent_passwd[target_user][4] }}"
    creates: "{{ getent_passwd[target_user][4] }}/.config/chezmoi/chezmoi.toml"

- name: Configure dotfiles theme
  become: true
  become_user: "{{ target_user }}"
  ansible.builtin.lineinfile:
    path: "{{ getent_passwd[target_user][4] }}/.config/chezmoi/chezmoi.toml"
    regexp: '^\s*theme_name\s*='
    line: '  theme_name = "{{ chezmoi_theme_name }}"'
    insertafter: '^\[data\]$'

- name: Apply user dotfiles
  become: true
  become_user: "{{ target_user }}"
  ansible.builtin.command:
    argv:
      - /usr/bin/chezmoi
      - --force
      - --no-tty
      - --verbose
      - apply
    chdir: "{{ getent_passwd[target_user][4] }}"
  register: _chezmoi_apply
  changed_when: _chezmoi_apply.stdout | trim | length > 0
