---
- name: Restart Docker with changed daemon configuration
  ansible.builtin.service:
    name: "{{ _docker_service_name }}"
    enabled: true
    state: restarted
  when:
    - _docker_daemon_configuration is defined
    - _docker_daemon_configuration is changed

- name: Enable and start Docker service
  ansible.builtin.service:
    name: "{{ _docker_service_name }}"
    enabled: true
    state: started
  when: >-
    _docker_daemon_configuration is not defined
    or _docker_daemon_configuration is not changed

- name: Report Docker service phase
  ansible.builtin.include_role:
    name: common
    tasks_from: report_phase.yml
  vars:
    common_rpt_fact: "_docker_phases"
    common_rpt_phase: "Apply service policy"
    common_rpt_status: "done"
    common_rpt_detail: "{{ _docker_service_name }}"
