---
- name: Validate Caddy platform
  ansible.builtin.assert:
    that:
      - ansible_facts['os_family'] in _caddy_supported_os
    fail_msg: "Caddy does not support {{ ansible_facts['os_family'] }}."

- name: Validate Caddy TLS mode
  ansible.builtin.assert:
    that:
      - caddy_tls_mode in ['internal', 'acme']
    fail_msg: "caddy_tls_mode must be internal or acme."

- name: Validate Caddy ACME account
  ansible.builtin.assert:
    that:
      - caddy_tls_email | length > 0
    fail_msg: "caddy_tls_email is required when caddy_tls_mode is acme."
  when: caddy_tls_mode == 'acme'
