---
# === gpu_drivers / install / NVIDIA ===

- name: "Install NVIDIA proprietary drivers"
  ansible.builtin.include_tasks:
    file: common/install_packages.yml
  vars:
    _gpu_drivers_package_stack: "{{ _gpu_drivers_debian_nvidia_proprietary }}"
  when: gpu_drivers_nvidia_variant == 'proprietary'

- name: "Install NVIDIA open kernel modules"
  ansible.builtin.include_tasks:
    file: common/install_packages.yml
  vars:
    _gpu_drivers_package_stack: "{{ _gpu_drivers_debian_nvidia_open }}"
  when: gpu_drivers_nvidia_variant == 'open-kernel'

- name: "Install NVIDIA VA-API driver"
  ansible.builtin.include_tasks:
    file: common/install_packages.yml
  vars:
    _gpu_drivers_package_stack: "{{ _gpu_drivers_debian_nvidia_vaapi }}"
  when:
    - gpu_drivers_nvidia_variant in ['proprietary', 'open-kernel']
    - gpu_drivers_vaapi
